# Generated by Django 3.2.9 on 2021-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
