# Generated by Django 3.2.9 on 2021-11-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docc', '0002_runner_medal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='medal',
        ),
    ]
