# Generated by Django 3.2.9 on 2021-11-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docc', '0003_remove_runner_medal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
