# Generated by Django 3.2.9 on 2021-11-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docc', '0006_pizza_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
