# Generated by Django 3.2.9 on 2021-11-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docc', '0010_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
