# Generated by Django 3.2.9 on 2021-11-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docc', '0011_person_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
