# Generated by Django 3.2.9 on 2021-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20211130_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10)),
            ],
        ),
    ]
