# Generated by Django 4.0 on 2021-12-11 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, help_text='Enter your nickname', max_length=50, null=True, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('childrens', models.IntegerField(blank=True, choices=[(1, '1'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True)),
                ('from_usa', models.BooleanField(default=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('time_under_water', models.DurationField(blank=True, null=True, verbose_name='Under Water time')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('filee', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
                ('height', models.FloatField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('about_yourself', models.TextField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('your_site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(through='doc4.Membership', to='doc4.Person')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc4.team'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc4.person'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(limit_choices_to={'birthday__lte': datetime.date(2003, 12, 11)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc4.person')),
            ],
        ),
    ]
