# Generated by Django 4.0 on 2021-12-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc4', '0002_membership_inviter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doc4.person')),
            ],
        ),
    ]
