# Generated by Django 4.0 on 2022-01-02 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc4', '0003_specialperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(limit_choices_to={'birthday__lte': datetime.date(2004, 1, 2)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc4.person'),
        ),
    ]
