# Generated by Django 4.0 on 2022-01-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
