# Generated by Django 4.0 on 2022-01-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='maichimp_msg',
            new_name='mailchimp_msg',
        ),
    ]
