# Generated by Django 3.2.9 on 2021-12-04 17:18

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_portfolio_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio_site',
            field=models.URLField(blank=True, validators=[accounts.validators.CustomURLValidator()]),
        ),
    ]
