# Generated by Django 3.2.9 on 2021-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
