# Generated by Django 3.2.9 on 2021-11-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_flavor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flavor',
        ),
    ]
