# Generated by Django 3.2.9 on 2021-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_note_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
