# Generated by Django 4.0 on 2022-02-09 13:32

from os import remove
from django.db import migrations

TAGS = (
    ('augmented_reality', 'augmented-reality'),
)

def add_tag_data(apps, schema_editor):
    Tag = apps.get_model('organizer', 'Tag')
    for tag_name, tag_slug in TAGS:
        Tag.objects.create(
            name=tag_name,
            slug=tag_slug
        )

def remove_tag_data(apps, schema_editor):
    Tag = apps.get_model('organizer', 'Tag')
    for _, tag_slug in TAGS:
        tag = Tag.objects.get(slug=tag_slug)
        tag.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tag_data,
            remove_tag_data,
        )
    ]
