# Generated by Django 4.0 on 2022-02-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_startup_data'),
    ]

    operations = [
    ]
