# Generated by Django 4.0 on 2022-02-10 12:07

from __future__ import unicode_literals

from functools import reduce
from operator import or_

from django.db import migrations, models
from django.db.models import Q

TAGS = (
    # ( tag name, tag slug ),
    ("big data", "big-data"),
    ("education", "education"),
    ("ipython", "ipython"),
    ("javascript", "javascript"),
    ("jupyter", "jupyter"),
    ("node.js", "node-js"),
    ("php", "php"),
    ("python", "python"),
    ("ruby on rails", "ruby-on-rails"),
    ("ruby", "ruby"),
    ("zend", "zend"),
)


def add_tag_data(apps, schema_editor):
    Tag = apps.get_model('organizer', 'Tag')
    tag_list = []
    for tag_name, tag_slug in TAGS:
        tag_list.append(
            Tag(name=tag_name, slug=tag_slug))
    Tag.objects.bulk_create(tag_list)


def remove_tag_data(apps, schema_editor):
    Tag = apps.get_model('organizer', 'Tag')
    query_list = []
    for _, tag_slug in TAGS:
        query_list.append(
            Q(slug=tag_slug))
    query = reduce(or_, query_list)
    Tag.objects.filter(query).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_alter_startup_tags'),
    ]

    operations = [
        migrations.RunPython(
            add_tag_data,
        )
    ]
