# Generated by Django 4.0 on 2022-01-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_orders', '0006_productpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='orde_id',
            field=models.CharField(default='abc123', max_length=120),
            preserve_default=False,
        ),
    ]
