# Generated by Django 4.0 on 2022-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_orders', '0007_remove_productpurchase_user_productpurchase_orde_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='orde_id',
            new_name='order_id',
        ),
    ]
