# Generated by Django 4.0 on 2022-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_billing', '0002_alter_billingprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
