# Generated by Django 4.0 on 2022-01-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_billing', '0004_cardmanager_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardManager',
        ),
    ]
