# Generated by Django 4.0 on 2022-01-23 09:41

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='filename',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/projects/protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
