# Generated by Django 4.0 on 2022-01-23 14:39

import config.storage_backends
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productfile_free_productfile_user_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=config.storage_backends.ProtectedMediaStorage(), upload_to=products.models.upload_product_file_loc),
        ),
    ]
